# Generated by Django 5.1.3 on 2024-12-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_jobpostcomment_comment_parent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostcomment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
