# Generated by Django 5.0.3 on 2024-10-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_wage_per_hour_jobpost_wage_per_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='background_desired',
            field=models.CharField(blank=True, choices=[('high_school_diploma', 'Có bằng tốt nghiệp trung học phổ thông'), ('bachelor_degree', 'Có bằng cử nhân'), ('bachelor_degree_engineering', 'Có bằng kĩ sư'), ('master_degree', 'Có bằng thạc sĩ'), ('doctorate_degree', 'Có bằng tiến sĩ')], max_length=255),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='duration',
            field=models.FloatField(blank=True),
        ),
    ]
