# Generated by Django 5.0.3 on 2024-10-04 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_jobpost_background_desired_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='parent_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
