# Generated by Django 5.0.3 on 2024-10-05 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_jobpost_parent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classtime',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_times', to='accounts.jobpost'),
        ),
    ]
