# Generated by Django 5.0.3 on 2024-10-13 10:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_classtime_post_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobregister',
            name='id',
        ),
        migrations.AddField(
            model_name='jobregister',
            name='registration_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='background_desired',
            field=models.CharField(blank=True, choices=[('high_school_diploma', 'Có bằng tốt nghiệp trung học phổ thông'), ('university_student', 'Sinh viên'), ('university_graduate', 'Tốt nghiệp đại học'), ('university_graduate_education', 'Tốt nghiệp đại học sư phạm'), ('other', 'Khác')], max_length=255),
        ),
        migrations.AlterField(
            model_name='jobregister',
            name='tutor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='educational_background',
            field=models.CharField(blank=True, choices=[('high_school_diploma', 'Có bằng tốt nghiệp trung học phổ thông'), ('university_student', 'Sinh viên'), ('university_graduate', 'Tốt nghiệp đại học'), ('university_graduate_education', 'Tốt nghiệp đại học sư phạm'), ('other', 'Khác')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('tutor', 'Gia sư'), ('parent', 'Phụ huynh'), ('admin', 'Quản trị viên')], max_length=50),
        ),
    ]
