# Generated by Django 5.0.3 on 2024-10-13 12:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_jobregister_id_jobregister_registration_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobregister',
            name='registration_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
