# Generated by Django 5.1.3 on 2024-11-27 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_notification_data'),
        ('application', '0002_alter_jobpostcomment_comment_parent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.jobpostcomment'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('feedback', 'Đánh giá'), ('post', 'Bài đăng'), ('comment', 'Bình luận')], max_length=50),
        ),
    ]
